### ISSUE TITLE
Translated json files are wrapped in define()

### ISSUE THREAD

**Issue by coelacanth7** [tomaszbrue/i18n-translate#4]
I'm not sure if this is an issue or if my arguments in the cli are wrong.

Running:
`
i18n-translate API_KEY public/locales en es
`
On this in public/locales:
`
{
  "root": {
    "test": "hello"
  }
}
`

Gives me a translated json file that looks like this:

`
define({
	"test": "Hola"
});
`

This is not ideal because for npm i18next this is not a valid json format and I have to delete the define() function in each json. I am translating 14 languages each time so this is time-consuming.

Otherwise the software works great! Thank you!

**Comment by coelacanth7** [comment]
I figured out that if I comment out lines 145 and 156 then I can remove this side effect. Is there a better way?

**Comment by thomasbrueggemann** [comment]
Well, this repository was created to translate http://requirejs.org/docs/api.html#i18n messages. At the time, the define() was necessary and it seems that it still is.
So it's not a side effect, you just use this tool for something it was not build for.
If you want to use this tool for any other purpose, like i18next, there are two options I guess:

1) you fork this repository and build a i18next version
2) you submit a pull-request that implements a CLI switch that lets users select the output format (e.g. i18next, requirejs-i18n, ...)
